version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  seq:
    container_name: seq
    image: datalust/seq
    ports:
      - "8003:80"
      - "5341:5341"
    environment:
      ACCEPT_EULA: "Y"
  redis:
    container_name: redis
    image: docker.io/library/redis:alpine
    ports:
      - "6379:6379"